# Keep every hardware output of the Komplete Audio 6 MK2 available.
monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-Native_Instruments_Komplete_Audio_6_MK2_BE1EB8C5-00"
      }
    ]
    actions = {
      update-props = {
        device.profile = "pro-audio"
      }
    }
  }
]
