# Expose the Komplete Audio 6 MK2's four analog capture channels as
# individually named mono sources for applications such as Bitwig.
context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Komplete Input 1"
            capture.props = {
                audio.position = [ FL ]
                stream.dont-remix = true
                target.object = "alsa_input.usb-Native_Instruments_Komplete_Audio_6_MK2_BE1EB8C5-00.analog-stereo-in-ab"
                node.passive = true
            }
            playback.props = {
                node.name = "komplete_audio_6_input_1"
                media.class = "Audio/Source"
                audio.position = [ MONO ]
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Komplete Input 2"
            capture.props = {
                audio.position = [ FR ]
                stream.dont-remix = true
                target.object = "alsa_input.usb-Native_Instruments_Komplete_Audio_6_MK2_BE1EB8C5-00.analog-stereo-in-ab"
                node.passive = true
            }
            playback.props = {
                node.name = "komplete_audio_6_input_2"
                media.class = "Audio/Source"
                audio.position = [ MONO ]
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Komplete Input 3"
            capture.props = {
                audio.position = [ AUX0 ]
                stream.dont-remix = true
                target.object = "alsa_input.usb-Native_Instruments_Komplete_Audio_6_MK2_BE1EB8C5-00.analog-stereo-in-ab"
                node.passive = true
            }
            playback.props = {
                node.name = "komplete_audio_6_input_3"
                media.class = "Audio/Source"
                audio.position = [ MONO ]
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Komplete Input 4"
            capture.props = {
                audio.position = [ AUX1 ]
                stream.dont-remix = true
                target.object = "alsa_input.usb-Native_Instruments_Komplete_Audio_6_MK2_BE1EB8C5-00.analog-stereo-in-ab"
                node.passive = true
            }
            playback.props = {
                node.name = "komplete_audio_6_input_4"
                media.class = "Audio/Source"
                audio.position = [ MONO ]
            }
        }
    }
]
